[tool.pytest.ini_options]
markers = """slow: marks tests as slow (deselect with '-m "not slow"')"""
filterwarnings = [
    "ignore:Keyword argument 'eigvals' is deprecated*:DeprecationWarning:wpca.*:",
]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.black]
line-length = 120
target-version = "py310"
